# Generated by Django 5.1.7 on 2025-03-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='CampaignDetails',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=30)),
                ('campaign_description', models.CharField(max_length=255)),
                ('campaign_start_date', models.DateTimeField()),
                ('campaign_end_date', models.DateTimeField()),
                ('campaign_mail_body', models.TextField()),
                ('campaign_mail_subject', models.CharField(max_length=255)),
                ('send_time', models.DateTimeField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_details', to='api.organization', to_field='org_id')),
            ],
            options={
                'db_table': 'campaign_details',
            },
        ),
        migrations.CreateModel(
            name='CampaignStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_click_rate', models.FloatField()),
                ('user_open_rate', models.FloatField()),
                ('user_engagement_delay', models.FloatField()),
                ('user_engagement_rate', models.FloatField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_statistics', to='api.campaigndetails')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_campaign_statistics', to='api.organization', to_field='org_id')),
            ],
            options={
                'db_table': 'campaign_statistics',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='api.organization', to_field='org_id')),
            ],
            options={
                'db_table': 'company_users',
            },
        ),
        migrations.CreateModel(
            name='CompanyUserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('open_time', models.DateTimeField(blank=True, null=True)),
                ('click_rate', models.FloatField()),
                ('open_rate', models.FloatField()),
                ('engagement_delay', models.FloatField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_user_engagement', to='api.campaigndetails')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_user_engagement', to='api.organization', to_field='org_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user_engagement', to='api.companyuser')),
            ],
            options={
                'db_table': 'company_user_engagement',
            },
        ),
    ]
