# Generated by Django 5.1.7 on 2025-03-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emaillog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emaillog',
            table='email_log',
        ),
    ]
