# Generated by Django 5.1.7 on 2025-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emaillog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
