# Generated by Django 5.1.7 on 2025-03-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emaillog_status_alter_emaillog_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuserengagement',
            name='click_rate',
        ),
        migrations.RemoveField(
            model_name='companyuserengagement',
            name='open_rate',
        ),
    ]
