# Generated by Django 5.1.6 on 2025-04-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_companyuserengagement_click_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstatistics',
            name='user_engagement_rate',
        ),
    ]
