# Generated by Django 5.1.7 on 2025-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_campaignstatistics_user_engagement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserengagement',
            name='click_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
